import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
data = pd.read_csv("Titanic Dataset.csv")
data.head(5)
sns.countplot(data["Gender"],hue=data["Survived"])
plt.show()
sns.countplot(data["Pclass"],hue=data["Survived"])
plt.show()
sns.distplot(data["Age"],kde=False,bins=40)
plt.show()
sns.countplot(data["Gender"])
plt.show()
sns.countplot(x="Survived",hue="SibSp",data=data,palette="mako")
plt.show()
sns.countplot(x="Survived",hue="Parch",data=data,palette="mako")
plt.show()
sns.distplot(data["Fare"])
plt.show()
sns.boxplot(x="Pclass",y="Age",data=data,palette="winter")
sns.heatmap(data.corr())